[package]
name = "periodic-api"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = "0.4.1"
rocket_codegen = "0.4.1"
rocket_contrib = "0.4.2"
serde = { version = "1.0.97", features = ["derive"] }
serde_json = "1.0.40"
